name: ggsn_proj
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - ipykernel
      - tqdm
      - joblib
      - ipywidgets
      - nltk
      - scikit-image
      - lime
      - captum
      - shap
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - transformers
      - datasets
      - evaluate
      - accelerate
      - sentencepiece
