name: ggsn_ex1
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - ipykernel
      - xgboost
      - imbalanced-learn
      - shap
      - tensorflow==2.20.*
